<FraudAnalysis>	
	<FraudScoreIndicator>[% FraudScoreIndicator= %]</FraudScoreIndicator>
	<RulesTrigger>[% RulesTrigger= %]</RulesTrigger>
	<SafetechMerchantID>[% SafetechMerchantID= %]</SafetechMerchantID>
	<KaptchaSessionID>[% KaptchaSessionID= %]</KaptchaSessionID>
	<WebsiteShortName>[% WebsiteShortName= %]</WebsiteShortName>
	<CashValueOfFencibleItems>[% CashValueOfFencibleItems= %]</CashValueOfFencibleItems>
	<CustomerDOB>[% CustomerDOB= %]</CustomerDOB>
	<CustomerGender>[% CustomerGender= %]</CustomerGender>
	<CustomerDriverLicense>[% CustomerDriverLicense= %]</CustomerDriverLicense>
	<CustomerID>[% CustomerID= %]</CustomerID>
	<CustomerIDCreationTime>[% CustomerIDCreationTime= %]</CustomerIDCreationTime>
	<KTTVersionNumber>[% KTTVersionNumber= %]</KTTVersionNumber>
	<KTTDataLength>[% KTTDataLength= %]</KTTDataLength>
	<KTTDataString>[% KTTDataString= %]</KTTDataString>
</FraudAnalysis>
