<SoftMerchantDescriptors>	
	<SMDDBA>[% SMDDBA= %]</SMDDBA>
	<SMDMerchantID>[% SMDMerchantID= %]</SMDMerchantID>
	<SMDContactInfo>[% SMDContactInfo= %]</SMDContactInfo>
	<SMDStreet>[% SMDStreet= %]</SMDStreet>
	<SMDCity>[% SMDCity= %]</SMDCity>
	<SMDRegion>[% SMDRegion= %]</SMDRegion>
	<SMDPostalCode>[% SMDPostalCode= %]</SMDPostalCode>
	<SMDCountryCode>[% SMDCountryCode= %]</SMDCountryCode>
	<SMDMCC>[% SMDMCC= %]</SMDMCC>
	<SMDEmail>[% SMDEmail= %]</SMDEmail>
	<SMDPhoneNumber>[% SMDPhoneNumber= %]</SMDPhoneNumber>
</SoftMerchantDescriptors>
